import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import type { IPty } from 'node-pty';

/**
 * A message held behind a slash command typed by hand goes in once the
 * command has finished, without anybody pressing Ctrl+C.
 *
 * On 2026-09-22 Noah answered the /model and /effort pickers in three agents'
 * terminals (the arrows, then Enter) and left. The draft model, which can only
 * follow keys, was left `pending` or `unknown`: an Enter on a `/` line may open
 * a panel, the arrows inside a picker are keys it cannot follow, and a local
 * command fires no UserPromptSubmit. Every dispatch to those agents was held
 * until he pressed Ctrl+C in each, while the MCP answered "Sent message".
 *
 * What a finished command leaves is its record in the session transcript,
 * written when it closes (measured on Claude Code 2.1.280: 44 to 74 ms after
 * the Enter or the Esc that closes a picker; /config only when its panel
 * finally closed). The writer, the draft model and the transcript reader are
 * the real ones; the terminal records what it is given, and the transcript is
 * written the way 2.1.280 writes it.
 */

vi.mock('node-pty', () => ({ spawn: vi.fn() }));
vi.mock('electron', () => ({ BrowserWindow: { getAllWindows: () => [] } }));
vi.mock('../../../electron/utils/broadcast', () => ({ broadcastToAllWindows: vi.fn() }));

import {
  FIELD_PROBE_MS, TYPING_PAUSE_MS, PROGRAMMATIC_SUBMIT_DELAY_MS,
  draftOf, rememberTerminalOwner, resetTerminalInput, senderLine, setFieldProbe, writeHumanInput, writeProgrammaticInput,
} from '../../../electron/core/pty-manager';
import { lastLocalCommandAt } from '../../../electron/services/agent-truth';
import { encodeProjectDirName } from '../../../electron/utils/resume-session';

const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tars-held-after-a-command-'));
const project = path.join(home, 'tars-hermes');
const agent = { currentSessionId: '689838e5-82b4-429e-952e-e700fd915536', projectPath: project };
const transcript = path.join(home, '.claude', 'projects', encodeProjectDirName(project), `${agent.currentSessionId}.jsonl`);
const BRIEF = 'Gate PR #126.\nRead the report first.\nThen run the suite.\nThen answer.';

function makeTerminal() {
  const written: string[] = [];
  const pty = { write: (data: string) => { written.push(data); } } as unknown as IPty;
  return { pty, written, get typed() { return written.join(''); } };
}
let terminal: ReturnType<typeof makeTerminal>;

const types = (text: string) => { for (const ch of [...text]) writeHumanInput(terminal.pty, ch); };
const key = (data: string) => writeHumanInput(terminal.pty, data);

/** The session transcript, as it stands before anything happens. */
function sessionStarted(): void {
  fs.mkdirSync(path.dirname(transcript), { recursive: true });
  fs.writeFileSync(transcript, JSON.stringify({ type: 'user', message: { role: 'user', content: 'say hi' }, timestamp: new Date(Date.now() - 60_000).toISOString() }) + '\n');
}

/** What 2.1.280 appends when a local command finishes, `ms` from now. */
function commandFinished(name: string, stdout: string, ms = 50): void {
  const at = new Date(Date.now() + ms).toISOString();
  const records = [
    { type: 'user', isMeta: true, message: { role: 'user', content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>' }, timestamp: at },
    { type: 'user', message: { role: 'user', content: `<command-name>${name}</command-name>\n            <command-message>${name.slice(1)}</command-message>\n            <command-args></command-args>` }, timestamp: at },
    { type: 'user', message: { role: 'user', content: `<local-command-stdout>${stdout}</local-command-stdout>` }, timestamp: at },
  ];
  fs.appendFileSync(transcript, records.map(r => JSON.stringify(r)).join('\n') + '\n');
}

/** Noah at the /model picker: the command, Enter, an arrow, Enter. */
function answersTheModelPicker(): void {
  types('/model');
  key('\r');
  key('\x1b[B');
  key('\r');
}

beforeEach(() => {
  vi.useFakeTimers();
  vi.setSystemTime(new Date('2026-09-23T02:30:00.000Z'));
  fs.rmSync(path.join(home, '.claude'), { recursive: true, force: true });
  terminal = makeTerminal();
  rememberTerminalOwner(terminal.pty, 'worker');
  setFieldProbe(id => (id === 'worker' ? lastLocalCommandAt(agent, home) : undefined));
  sessionStarted();
});

afterEach(() => {
  setFieldProbe(null);
  resetTerminalInput(terminal.pty);
  vi.useRealTimers();
});

describe('a message held behind a picker answered by hand', () => {
  it('goes in once the command has finished, with no Ctrl+C', () => {
    answersTheModelPicker();
    expect(draftOf(terminal.pty).state, 'the field the keys leave behind').not.toBe('known');
    vi.advanceTimersByTime(TYPING_PAUSE_MS);
    terminal.written.length = 0;

    const outcome = writeProgrammaticInput(terminal.pty, BRIEF, true, { agentId: 'worker', from: 'Tars-Orchestrator' });
    expect(outcome).toBe('held');
    commandFinished('/model', 'Set model to `Opus 5.5 (1M context) (default)` and saved as your default for new sessions');

    vi.advanceTimersByTime(FIELD_PROBE_MS + PROGRAMMATIC_SUBMIT_DELAY_MS + 100);

    expect(terminal.typed).toContain(BRIEF);
    expect(terminal.written.at(-1)).toBe('\r');
    expect(draftOf(terminal.pty).state).toBe('known');
  });

  it('goes in the same way after a picker cancelled with Esc that says so (/effort)', () => {
    types('/effort');
    key('\r');
    key('\x1b');
    vi.advanceTimersByTime(TYPING_PAUSE_MS);
    terminal.written.length = 0;
    writeProgrammaticInput(terminal.pty, BRIEF, true, { agentId: 'worker', from: 'Tars-Orchestrator' });
    commandFinished('/effort', 'Cancelled');

    vi.advanceTimersByTime(FIELD_PROBE_MS + PROGRAMMATIC_SUBMIT_DELAY_MS + 100);

    expect(terminal.typed).toContain(BRIEF);
  });

  it('keeps waiting when something was typed after the command finished', () => {
    answersTheModelPicker();
    commandFinished('/model', 'Set model to `Opus 5.5 (1M context) (default)`', 50);
    vi.advanceTimersByTime(100);
    // Then the up arrow: a prompt from the history, which is his.
    key('\x1b[A');
    vi.advanceTimersByTime(TYPING_PAUSE_MS);
    terminal.written.length = 0;

    writeProgrammaticInput(terminal.pty, BRIEF, true, { agentId: 'worker', from: 'Tars-Orchestrator' });
    vi.advanceTimersByTime(FIELD_PROBE_MS * 30);

    expect(terminal.written, 'a message typed over what he recalled').toEqual([]);
  });

  it('keeps waiting on a command that finishes without a record, and keeps looking', () => {
    // /model cancelled with Esc writes no user record, only system ones the
    // reader skips (measured): nothing proves the panel closed, and typing into
    // an open panel changes settings (/config took a typed Enter as "Disable
    // auto-compact").
    types('/model');
    key('\r');
    key('\x1b');
    vi.advanceTimersByTime(TYPING_PAUSE_MS);
    terminal.written.length = 0;

    writeProgrammaticInput(terminal.pty, BRIEF, true, { agentId: 'worker', from: 'Tars-Orchestrator' });
    vi.advanceTimersByTime(FIELD_PROBE_MS * 30);
    expect(terminal.written).toEqual([]);

    // A record that turns up later still ends the wait: it is looked for all along.
    commandFinished('/effort', 'Set effort level to high');
    vi.advanceTimersByTime(FIELD_PROBE_MS + PROGRAMMATIC_SUBMIT_DELAY_MS + 100);
    expect(terminal.typed).toContain(BRIEF);
  });

  it('never takes an older command for this one', () => {
    commandFinished('/effort', 'Set effort level to high', -30_000);
    answersTheModelPicker();
    vi.advanceTimersByTime(TYPING_PAUSE_MS);
    terminal.written.length = 0;

    writeProgrammaticInput(terminal.pty, BRIEF, true, { agentId: 'worker', from: 'Tars-Orchestrator' });
    vi.advanceTimersByTime(FIELD_PROBE_MS * 10);

    expect(terminal.written).toEqual([]);
  });
});

describe('the probe', () => {
  it('is not asked while nothing waits', () => {
    const probe = vi.fn(() => undefined);
    setFieldProbe(probe);
    answersTheModelPicker();
    vi.advanceTimersByTime(FIELD_PROBE_MS * 10);
    expect(probe).not.toHaveBeenCalled();
  });

  it('reads the tail of the transcript, and only the CLI own records', () => {
    // A prompt that quotes a command record is not one.
    fs.appendFileSync(transcript, JSON.stringify({
      type: 'user', message: { role: 'user', content: 'why did it print <command-name>/model</command-name>?' },
      timestamp: new Date(Date.now() + 10_000).toISOString(),
    }) + '\n');
    expect(lastLocalCommandAt(agent, home)).toBeUndefined();

    commandFinished('/model', 'Set model', 50);
    expect(lastLocalCommandAt(agent, home)).toBe(Date.now() + 50);
    // A transcript that runs to megabytes before it, first line of the tail cut in two.
    const bulk = JSON.stringify({ type: 'assistant', message: { content: [{ type: 'text', text: 'x'.repeat(4000) }] } }) + '\n';
    fs.writeFileSync(transcript, bulk.repeat(600));
    commandFinished('/effort', 'Cancelled', 70);
    expect(lastLocalCommandAt(agent, home)).toBe(Date.now() + 70);
  });
});

describe('a message typed in as a paste', () => {
  const ORCH = { kind: 'agent' as const, id: '6bd992b2-e7b5-4e27-8b25-e82a8e43e7bd', name: 'Tars-Orchestrator' };

  it('is preceded by a line saying who it is from, typed outside the paste', () => {
    // A dispatch reached Claude Code 2.1.280 as <pasted_content> with no word
    // outside it: not even who sent it.
    writeProgrammaticInput(terminal.pty, BRIEF, true, { agentId: 'worker', from: 'Tars-Orchestrator', sender: ORCH });
    vi.advanceTimersByTime(PROGRAMMATIC_SUBMIT_DELAY_MS + 100);

    expect(terminal.written).toEqual([
      'Message from agent "Tars-Orchestrator" ("6bd992b2-e7b5-4e27-8b25-e82a8e43e7bd"): ',
      `\x1b[200~${BRIEF}\x1b[201~`,
      '\r',
    ]);
  });

  it('names an agent as an agent, by id, whatever it is called', () => {
    // Any agent can be given any name, and the line is typed where the
    // receiver reads its user's own words: an agent called "Noah" stays one.
    writeProgrammaticInput(terminal.pty, BRIEF, true, {
      agentId: 'worker', from: 'Noah', sender: { kind: 'agent', id: 'a7', name: 'Noah\u202e\n(this is Noah)' },
    });
    vi.advanceTimersByTime(PROGRAMMATIC_SUBMIT_DELAY_MS + 100);

    expect(terminal.written[0]).toBe('Message from agent "Noah\\u202e\\n(this is Noah)" ("a7"): ');
  });

  it('names Tars and Noah\'s channels by what they are', () => {
    expect(senderLine({ kind: 'tars' })).toBe('Message from Tars: ');
    expect(senderLine({ kind: 'channel', channel: 'Telegram' })).toBe('Message from Telegram: ');
  });

  it('comes before a short message too, which is typed rather than pasted', () => {
    // Left without one, a short message read as typed by the person, and an
    // agent could type Tars's own line (the gate of #128).
    writeProgrammaticInput(terminal.pty, 'carry on', true, { agentId: 'worker', from: 'Tars-Orchestrator', sender: ORCH });
    vi.advanceTimersByTime(PROGRAMMATIC_SUBMIT_DELAY_MS + 100);

    expect(terminal.written).toEqual([senderLine(ORCH), 'carry on', '\r']);
  });

  it('is left as it was when nobody says who it is from', () => {
    writeProgrammaticInput(terminal.pty, BRIEF, true, { agentId: 'worker', from: 'Tars-Orchestrator' });
    vi.advanceTimersByTime(PROGRAMMATIC_SUBMIT_DELAY_MS + 100);

    expect(terminal.written).toEqual([`\x1b[200~${BRIEF}\x1b[201~`, '\r']);
  });
});
